### ISSUE TITLE
666 values in es & us group_vars

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/ofn-install#109]
both files include

```yaml
s3_backups_bucket: none
s3_access_key: 666
s3_secret: 666

stripe_client_id: 666
stripe_instance_secret_key: 666
```

this seems like some kind of workaround. i just tried to provision a server using playbooks from this repo and my first attempt failed with: `AnsibleUndefinedVariable: 's3_access_key' is undefined`

i also wonder why those 'secrets' don't go to git ignored `secrets.yaml` in `host_vars`?
