### ISSUE TITLE
Fetch ssh keys from URL (e.g. github profile)

### ISSUE THREAD

**Issue by elf-pavlik** [openfoodfoundation/ofn-install#114]
http://docs.ansible.com/ansible/latest/authorized_key_module.html#examples
```yaml
- name: Set authorized key took from url
  authorized_key:
    user: charlie
    state: present
    key: https://github.com/charlie.keys
```

I would prefer to only include URL `https://github.com/elf-pavlik.keys` in this repo, this way when I change SSH key I only update it on github and don't have to make another commit in this repo.
