### ISSUE TITLE
"Using vagrant" guide step crash with: ERROR! Invalid options for include_role: apply

### ISSUE THREAD

**Issue by gentooza** [openfoodfoundation/ofn-install#553]
## Description
Hi!
first of all, I'm totally newbie using vagrant ansible, etc. In fact Ruby on Rails is a SCI-FI technology for me.
I'm trying to follow the guide to setup and deploy a new instance of openfoodnetwork, the easiest way to test it seems also to be using vagrant, so my steps:
(from a Ubuntu GNU/Linux 18.04 x86_64 machine)
```
sudo apt install vagrant ansible ansible-lint
```
so I have versions:
ansible 2.5.1
Vagrant 2.0.2
Virtualbox 5.2.34

I clone ofn-install and inside I execute:
```
bin/setup
```

I start vagrant:
```
vagrant up
```

and when I execute:
```
ansible-playbook site.yml --limit vagrant
```

I get in red:
```
ERROR! Invalid options for include_role: apply
```

it comes, I think, from playbooks/provision.yml
```
  tasks:
    - name: update local secrets files
      include_role:
        name: fetch_secrets
        apply:
         delegate_to: 127.0.0.1
      when: ( fetch_ofn_secrets is defined or lookup('env','FETCH_OFN_SECRETS') == 'TRUE' ) and inventory_hostname not in groups['local']
      run_once: true
```

and nothing is served at localhost:8080

Do I miss something?

## Expected Behavior
I expect to follow the guide steps and have ofn working as local instance

## Actual Behaviour
in step:
```
ansible-playbook site.yml --limit vagrant
```

I get in red:
```
ERROR! Invalid options for include_role: apply
```

## Your Environment
Ubuntu GNU/Linux 18.04 x86_64 machine
ansible 2.5.1
Vagrant 2.0.2
Virtualbox 5.2.34

---
thanks!
