### ISSUE TITLE
App migration to new server takes 3 hours

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn-install#575]
## Description

Matt moved the Australian OFN to a new server (#565). After preparing everything and transferring assets, the actual move caused a downtime of 3 hours. We can time it so that it's happening during the night but it's still very slow.

## Expected Behavior

The migration takes less than 20 minutes. I've done zero-downtime migrations before. Having a small downtime is much easier but doesn't need to take much longer than 5 minutes. It's only copying the database and restarting two services.

## Actual Behaviour

The migration took 3 hours.

## Steps to Reproduce

I can't find a description of @Matt-Yorkley's migration process. Can you point me to it?

I guess he did something like this:

1. `ansible-playbook playbooks/maintenance_mode.yml -l prod2.openfoodnetwork.org.au`
2. `ansible-playbook playbooks/db_backup.yml -l prod2.openfoodnetwork.org.au`
3. `ansible-playbook playbooks/db_restore.yml -l prod3.openfoodnetwork.org.au`
4. Edit nginx config on the old server to proxy to the new server.

And there were probably many other tasks done as well.

## Severity

bug-s3: a feature is broken but there is a workaround

Two ways at looking at it:
- The migration is a feature and I would say that 3 hours is too long (broken). The workaround is scheduling it very well and telling everybody beforehand.
- During those 3 hours everything is broken. The workaround is waiting a long time and scheduling your work so that it doesn't impact you too badly.

## Possible Fix

Transfer the database between servers directly which takes 2 minutes:
```sh
ssh offrance@openfoodfrance.org "pg_dump -h localhost -U ofn_user openfoodnetwork | gzip" > backup_20180809.sql.tgz
psql -h localhost -U ofn_user postgres -c "drop database openfoodnetwork"
psql -h localhost -U ofn_user postgres -c "create database openfoodnetwork"
zcat backup_20180809.sql.tgz | psql -h localhost -U ofn_user openfoodnetwork
```

The new server needs SSH access to the old server for this to work. A full description of my last migration:
https://community.openfoodnetwork.org/t/migrating-a-production-server/1271/2

**Comment by Matt-Yorkley** [comment]
The migration was really slow (and stressful), and by the time it finished it was really late in my timezone. A couple of smaller factors:

- Ansible tasks seem to run a lot slower in the Rimu servers in general, I'm not sure why?
- The database was 400MB

The main factor was the method of transfer, as noted above. During the initial download everything was fine, but the upload to the new server was incredibly slow. I think it could have partly been due to issues with my internet connection speed... :disappointed: 

The playbooks used in this migration were designed for transferring data from production to a dev or staging environment for debugging. We should definitely improve the transfer process and transfer the data directly between the two machines in future. I think we can use SSH forwarding here with Ansible, but it'll need some setup and testing.

**Comment by Matt-Yorkley** [comment]
Also I should have manually restarted the `unicorn` and `delayed_job` processes after it finished. As I said it was late at that point, so I had to hand things over to Maikel in the next timezone.

**Comment by mkllnk** [comment]
Thanks for the background, @Matt-Yorkley. The slowness of our server is the distance for you. That server is really fast for me but I always struggle with slow Ansible tasks when I do stuff in Europe or America.

I'm not sure what exactly Ansible is doing. It seems to create a new connection for every command and there is always a delay. I reckon, when I deploy a European server, the actual command execution is 5 minutes and the delays introduced by Ansible are 20 minutes. It's a big downside of Ansible.

The slowness is also a reason why I suggested a shell script for deploys in the past. It's so much faster. The other reason is that Ansible is about a final state while deployments are about changing states in a pre-defined sequence. I don't think it's the best tool for the job. But we have it working at the moment and it would be good to iterate on what we have and not rewrite everything again.

**Comment by kristinalim** [comment]
I came across the `pipelining` Ansible configuration which looks helpful for this issue: https://docs.ansible.com/ansible/2.4/intro_configuration.html#pipelining

> Enabling pipelining reduces the number of SSH operations required to execute a module on the remote server, by executing many ansible modules without actual file transfer. This can result in a very significant performance improvement when enabled, however when using “sudo:” operations you must first disable ‘requiretty’ in /etc/sudoers on all managed hosts.

**Comment by Matt-Yorkley** [comment]
We should make a sysadmin issue for trying that out and switching to it. It'll need a good amount of testing though :+1:

**Comment by Matt-Yorkley** [comment]
#588

**Comment by Matt-Yorkley** [comment]
We can use SSH agent forwarding to rsync db dumps directly between the two servers without having to create a mess with SSH keys. I'll make a playbook soon, but here's and example (which works):

```yaml
---

- name: Test rsync with SSH forwarding
  hosts: ofn_servers
  remote_user: "{{ user }}"

  vars:
    test_file: "rsync-test.txt"

  tasks:
    - name: create test file
      file:
        state: touch
        dest: "/home/{{ user }}/{{ test_file }}"

    - name: rsync file with ssh forwarding
      synchronize:
        mode: pull
        src: "/home/{{ user }}/{{ test_file }}"  # Source on target host specified in --limit
        dest: "/home/{{ user }}/{{ test_file }}" # Dest on host specified in {{ rsync_to }}
      vars:
        ansible_ssh_extra_args: '-o ForwardAgent=yes'
      delegate_to: "{{ groups[rsync_to][0] }}"
```

Usage: `ansible-playbook playbooks/sync-test.yml --limit uk-staging -e "rsync_to=fr-staging"`. This creates a file on on uk-staging and transfers it directly to fr-staging via rsync, without having to make a copy of the user's SSH keys on uk-staging.
